package enumerados;

public enum TipoProblema {

    ERRORES_DURANTE_LA_INSTALACION(2),
    CONFIGURACION_INCORRECTA(1),
    CONFLICTOS_DE_SOFTWARE(3),
    PROBLEMAS_DE_COMPATIBILIDAD(5),
    FALLO_EN_LA_APLICACION_DE_PARCHES(5),
    ERRORES_POST_ACTUALIZACION(2),
    ERRORES_DE_SOFTWARE_REMOTOS(1),
    PROBLEMAS_DE_CONECTIVIDAD(3),
    ASISTENCIA_EN_LA_RESOLUCION_DE_PROBLEMAS(3),
    RENDIMIENTO_LENTO(1),
    ERRORES_FRECUENTES(1),
    OPTIMIZACION_DEL_SISTEMA(2),
    ERRORES_DE_APLICACION(3),
    PROBLEMAS_DE_HARDWARE(4),
    PROBLEMAS_DE_RED(5),
    PERDIDA_DE_DATOS(6),
    PROBLEMAS_DE_RESPALDO(7),
    RECUPERACION_DE_DATOS_DESPUES_DE_FALLAS(1),
    PROBLEMAS_DE_USO_DEL_SOFTWARE(2),
    DIFICULTADES_EN_LA_ADOPCION_DE_NUEVAS_TECNOLOGIAS(3),
    ERRORES_FRECUENTES_DE_LOS_USUARIOS(4),
    VIRUS_Y_MALWARE(5),
    VIOLACIONES_DE_SEGURIDAD(6),
    CONFIGURACION_DE_CORTAFUEGOS_Y_ANTIVIRUS(7),
    PROBLEMAS_DE_RENDIMIENTO_NO_DETECTADOS(1),
    SUPERVISION_DE_RECURSOS_DEL_SISTEMA(2),
    ALERTAS_DE_RENDIMIENTO(3),
    PROBLEMAS_DE_INTEROPERABILIDAD(4),
    ERRORES_EN_LA_INTEGRACION(5),
    PROBLEMAS_DE_TRANSFERENCIA_DE_DATOS(6),
    NECESIDAD_DE_ASESORAMIENTO_TECNICO(7),
    OPTIMIZACION_DE_PROCESOS(1),
    EVALUACION_DE_TECNOLOGIAS_EMERGENTES(2),
    PROBLEMAS_DE_CUMPLIMIENTO_LEGAL(3),
    GESTION_DE_LICENCIAS_VENCIDAS(4),
    AUDITORIA_DE_SOFTWARE(5);

    private final long diasEstimados;

    TipoProblema(long diasEstimados) {
        this.diasEstimados = diasEstimados;
    }

    public long getDiasEstimados() {
        return diasEstimados;
    }
}
